import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import MainLayout from "@/components/layout/MainLayout";
import "../globals.css";

const inter = Poppins({ subsets: ["latin"], weight: "300" });

export const metadata: Metadata = {
  title: "FocusAI",
  description: "Generated by create next app",
  creator: "Petar Ivanov",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-screen bg-dark-gray-5">
          <MainLayout>{children}</MainLayout>
        </main>
      </body>
    </html>
  );
}
