import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import MainLayout from "@/components/main-layout";

const inter = Poppins({ subsets: ["latin"], weight: "300" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-screen bg-dark-gray-5">
          <MainLayout>{children}</MainLayout>
        </main>
      </body>
    </html>
  );
}
