import "reflect-metadata";
import "../globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import ClientExportReflect from "./client-reflect";

const inter = Poppins({ subsets: ["latin"], weight: "300" });

export const metadata: Metadata = {
  title: "FocusAI",
  description: "Generated by create next app",
  creator: "Petar Ivanov",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientExportReflect>
          <main className="min-h-screen bg-dark-gray-5">{children}</main>
        </ClientExportReflect>
      </body>
    </html>
  );
}
